### ISSUE TITLE
Installation does not really work

### ISSUE THREAD

**Issue by rabol** [sertxudeveloper/Lyra#4]
The installation documentation might need an update

executing the php artisan lyra:install asks a question and the documentation does not mention anything and no matter what one choose, the /lyra gives a 403 error

**Comment by sertxudeveloper** [comment]
I just tried it with a fresh installation of Laravel, in case you are using the basic mode you might get the 403 by having a session started without access permission to /lyra.

Check the working modes section:
https://lyra.sertxudeveloper.com/docs/en/v1.x/working-modes/working-modes.html#basic

**Comment by sertxudeveloper** [comment]
I found the problem, it's a bug in the LyraAdminMiddleware. I'm going to publish a new release in the next minutes to solve this issue.
