### ISSUE TITLE
Lyra doesnot really like debug bar

### ISSUE THREAD

**Issue by rabol** [sertxudeveloper/Lyra#5]
![Screenshot 2020-06-12 at 16 39 01](https://user-images.githubusercontent.com/1177191/84514457-59041600-accb-11ea-8ef4-40a076dba125.png)

Please see attached

I have a clean Laravel 7, with barryvdh/laravel-debugbar installed

**Comment by sertxudeveloper** [comment]
I am testing it and I have already found the problem, in the next patch version it will be solved.
