### ISSUE TITLE
Roadmap? Ability to define filters!

### ISSUE THREAD

**Issue by mustafa-online** [sertxudeveloper/Lyra#9]
Thanks for the this amzing package, I'm wondering if there is any roadmap or future plans.
One more thing: is there an ability to define filters in the backend?

**Comment by sertxudeveloper** [comment]
Hi, I'm glad you like the package.

Currently, I'm very busy 'cause I'm working full time in a business and in my free time I'm updating some old projects.

I have no well-defined roadmap actually, but I have in mind some big changes for the 2.0 version, like migrating from Bootstrap to Tailwind and updating all the Vuejs 2 code to the new Vuejs 3.

What type of filter would you like to add? Could you provide an example so I can understand exactly what you want to do?

**Comment by mustafa-online** [comment]
I'm having a new project, the clients wants to filter everything using combined fields, date-range, relationships, etc.

**Comment by sertxudeveloper** [comment]
By now there's no defined way to create filters nor date ranges.

The relationships are currently supported, you can learn more about it in the docs (https://lyra.sertxudeveloper.com/docs/en/v1.x/fields/relations.html).

In case you missed it there's an online demo where you can try the package without needing to install anything (https://lyra.sertxudeveloper.com/lyra).

**Comment by sertxudev** [comment]
I'm adding it to my roadmap, so for version 2.x, I will add a way to create custom filters.

By now I'm going to close this issue.

If you have another feature request, please let me know so I can make this library better.

Thanks, have a nice day.
